transcript on
if {[file exists rtl_work]} {
	vdel -lib rtl_work -all
}
vlib rtl_work
vmap work rtl_work

vlib platform
vmap platform platform
vlog -vlog01compat -work platform +incdir+C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/platform/synthesis {C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/platform/synthesis/platform.v}
vlog -vlog01compat -work platform +incdir+C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/platform/synthesis/submodules {C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/platform/synthesis/submodules/altera_reset_controller.v}
vlog -vlog01compat -work platform +incdir+C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/platform/synthesis/submodules {C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/platform/synthesis/submodules/altera_reset_synchronizer.v}
vlog -vlog01compat -work platform +incdir+C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/platform/synthesis/submodules {C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/platform/synthesis/submodules/platform_mm_interconnect_1.v}
vlog -vlog01compat -work platform +incdir+C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/platform/synthesis/submodules {C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/platform/synthesis/submodules/platform_mm_interconnect_0_avalon_st_adapter.v}
vlog -vlog01compat -work platform +incdir+C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/platform/synthesis/submodules {C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/platform/synthesis/submodules/altera_avalon_sc_fifo.v}
vlog -vlog01compat -work platform +incdir+C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/platform/synthesis/submodules {C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/platform/synthesis/submodules/platform_mm_interconnect_0.v}
vlog -vlog01compat -work platform +incdir+C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/platform/synthesis/submodules {C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/platform/synthesis/submodules/platform_mm_interconnect_0_avalon_st_adapter_001.v}
vlog -vlog01compat -work platform +incdir+C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/platform/synthesis/submodules {C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/platform/synthesis/submodules/platform_pll_1.v}
vlog -vlog01compat -work platform +incdir+C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/platform/synthesis/submodules {C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/platform/synthesis/submodules/platform_pll_0.v}
vlog -vlog01compat -work platform +incdir+C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/platform/synthesis/submodules {C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/platform/synthesis/submodules/platform_pio_0.v}
vlog -vlog01compat -work platform +incdir+C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/platform/synthesis/submodules {C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/platform/synthesis/submodules/platform_new_sdram_controller_0.v}
vlog -vlog01compat -work platform +incdir+C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/platform/synthesis/submodules {C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/platform/synthesis/submodules/platform_master_0.v}
vlog -vlog01compat -work platform +incdir+C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/platform/synthesis/submodules {C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/platform/synthesis/submodules/altera_avalon_packets_to_master.v}
vlog -vlog01compat -work platform +incdir+C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/platform/synthesis/submodules {C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/platform/synthesis/submodules/altera_avalon_st_packets_to_bytes.v}
vlog -vlog01compat -work platform +incdir+C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/platform/synthesis/submodules {C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/platform/synthesis/submodules/altera_avalon_st_bytes_to_packets.v}
vlog -vlog01compat -work platform +incdir+C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/platform/synthesis/submodules {C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/platform/synthesis/submodules/altera_avalon_st_jtag_interface.v}
vlog -vlog01compat -work platform +incdir+C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/platform/synthesis/submodules {C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/platform/synthesis/submodules/altera_jtag_dc_streaming.v}
vlog -vlog01compat -work platform +incdir+C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/platform/synthesis/submodules {C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/platform/synthesis/submodules/altera_jtag_sld_node.v}
vlog -vlog01compat -work platform +incdir+C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/platform/synthesis/submodules {C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/platform/synthesis/submodules/altera_jtag_streaming.v}
vlog -vlog01compat -work platform +incdir+C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/platform/synthesis/submodules {C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/platform/synthesis/submodules/altera_avalon_st_clock_crosser.v}
vlog -vlog01compat -work platform +incdir+C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/platform/synthesis/submodules {C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/platform/synthesis/submodules/altera_std_synchronizer_nocut.v}
vlog -vlog01compat -work platform +incdir+C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/platform/synthesis/submodules {C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/platform/synthesis/submodules/altera_avalon_st_idle_remover.v}
vlog -vlog01compat -work platform +incdir+C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/platform/synthesis/submodules {C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/platform/synthesis/submodules/altera_avalon_st_idle_inserter.v}
vlog -vlog01compat -work platform +incdir+C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/platform/synthesis/submodules {C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/platform/synthesis/submodules/platform_fifo_0.v}
vlog -vlog01compat -work platform +incdir+C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/platform/synthesis/submodules {C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/platform/synthesis/submodules/platform_dma_0.v}
vlog -sv -work work +incdir+C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/source {C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/source/reset.sv}
vlog -sv -work work +incdir+C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/source {C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/source/Video_Controller.sv}
vlog -sv -work work +incdir+C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/source {C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/source/vga_pixel_gen.sv}
vlog -sv -work work +incdir+C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/source {C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/source/vga_clock.sv}
vlog -sv -work platform +incdir+C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/platform/synthesis/submodules {C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/platform/synthesis/submodules/platform_mm_interconnect_0_avalon_st_adapter_error_adapter_0.sv}
vlog -sv -work platform +incdir+C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/platform/synthesis/submodules {C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/platform/synthesis/submodules/platform_mm_interconnect_1_rsp_mux.sv}
vlog -sv -work platform +incdir+C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/platform/synthesis/submodules {C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/platform/synthesis/submodules/altera_merlin_arbitrator.sv}
vlog -sv -work platform +incdir+C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/platform/synthesis/submodules {C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/platform/synthesis/submodules/platform_mm_interconnect_1_cmd_mux.sv}
vlog -sv -work platform +incdir+C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/platform/synthesis/submodules {C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/platform/synthesis/submodules/platform_mm_interconnect_1_cmd_demux.sv}
vlog -sv -work platform +incdir+C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/platform/synthesis/submodules {C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/platform/synthesis/submodules/altera_merlin_burst_adapter.sv}
vlog -sv -work platform +incdir+C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/platform/synthesis/submodules {C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/platform/synthesis/submodules/altera_merlin_burst_adapter_13_1.sv}
vlog -sv -work platform +incdir+C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/platform/synthesis/submodules {C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/platform/synthesis/submodules/altera_merlin_address_alignment.sv}
vlog -vlog01compat -work platform +incdir+C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/platform/synthesis/submodules {C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/platform/synthesis/submodules/altera_avalon_st_pipeline_base.v}
vlog -sv -work platform +incdir+C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/platform/synthesis/submodules {C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/platform/synthesis/submodules/platform_mm_interconnect_1_router_001.sv}
vlog -sv -work platform +incdir+C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/platform/synthesis/submodules {C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/platform/synthesis/submodules/platform_mm_interconnect_1_router.sv}
vlog -sv -work platform +incdir+C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/platform/synthesis/submodules {C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/platform/synthesis/submodules/altera_merlin_slave_agent.sv}
vlog -sv -work platform +incdir+C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/platform/synthesis/submodules {C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/platform/synthesis/submodules/altera_merlin_burst_uncompressor.sv}
vlog -sv -work platform +incdir+C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/platform/synthesis/submodules {C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/platform/synthesis/submodules/altera_merlin_master_agent.sv}
vlog -sv -work platform +incdir+C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/platform/synthesis/submodules {C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/platform/synthesis/submodules/altera_merlin_slave_translator.sv}
vlog -sv -work platform +incdir+C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/platform/synthesis/submodules {C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/platform/synthesis/submodules/altera_merlin_master_translator.sv}
vlog -sv -work platform +incdir+C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/platform/synthesis/submodules {C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/platform/synthesis/submodules/platform_mm_interconnect_0_avalon_st_adapter_001_error_adapter_0.sv}
vlog -sv -work platform +incdir+C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/platform/synthesis/submodules {C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/platform/synthesis/submodules/altera_merlin_width_adapter.sv}
vlog -sv -work platform +incdir+C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/platform/synthesis/submodules {C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/platform/synthesis/submodules/platform_mm_interconnect_0_rsp_mux_001.sv}
vlog -sv -work platform +incdir+C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/platform/synthesis/submodules {C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/platform/synthesis/submodules/platform_mm_interconnect_0_rsp_mux.sv}
vlog -sv -work platform +incdir+C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/platform/synthesis/submodules {C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/platform/synthesis/submodules/platform_mm_interconnect_0_rsp_demux_002.sv}
vlog -sv -work platform +incdir+C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/platform/synthesis/submodules {C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/platform/synthesis/submodules/platform_mm_interconnect_0_rsp_demux.sv}
vlog -sv -work platform +incdir+C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/platform/synthesis/submodules {C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/platform/synthesis/submodules/platform_mm_interconnect_0_cmd_mux_002.sv}
vlog -sv -work platform +incdir+C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/platform/synthesis/submodules {C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/platform/synthesis/submodules/platform_mm_interconnect_0_cmd_mux.sv}
vlog -sv -work platform +incdir+C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/platform/synthesis/submodules {C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/platform/synthesis/submodules/platform_mm_interconnect_0_cmd_demux_001.sv}
vlog -sv -work platform +incdir+C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/platform/synthesis/submodules {C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/platform/synthesis/submodules/platform_mm_interconnect_0_cmd_demux.sv}
vlog -sv -work platform +incdir+C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/platform/synthesis/submodules {C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/platform/synthesis/submodules/altera_merlin_traffic_limiter.sv}
vlog -sv -work platform +incdir+C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/platform/synthesis/submodules {C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/platform/synthesis/submodules/platform_mm_interconnect_0_router_004.sv}
vlog -sv -work platform +incdir+C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/platform/synthesis/submodules {C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/platform/synthesis/submodules/platform_mm_interconnect_0_router_003.sv}
vlog -sv -work platform +incdir+C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/platform/synthesis/submodules {C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/platform/synthesis/submodules/platform_mm_interconnect_0_router_002.sv}
vlog -sv -work platform +incdir+C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/platform/synthesis/submodules {C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/platform/synthesis/submodules/platform_mm_interconnect_0_router_001.sv}
vlog -sv -work platform +incdir+C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/platform/synthesis/submodules {C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/platform/synthesis/submodules/platform_mm_interconnect_0_router.sv}
vlog -sv -work platform +incdir+C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/platform/synthesis/submodules {C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/platform/synthesis/submodules/platform_master_0_p2b_adapter.sv}
vlog -sv -work platform +incdir+C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/platform/synthesis/submodules {C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/platform/synthesis/submodules/platform_master_0_b2p_adapter.sv}
vlog -sv -work platform +incdir+C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/platform/synthesis/submodules {C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/platform/synthesis/submodules/platform_master_0_timing_adt.sv}

vlog -sv -work work +incdir+C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/source {C:/Users/nickw/Documents/GitHub/ECEN_3002/ECEN_3002_FPGA_VLSI_Design/vga_controller/part_5/source/tb.sv}

vsim -t 1ps -L altera_ver -L lpm_ver -L sgate_ver -L altera_mf_ver -L altera_lnsim_ver -L cyclonev_ver -L cyclonev_hssi_ver -L cyclonev_pcie_hip_ver -L rtl_work -L work -L platform -voptargs="+acc"  tb

add wave *
view structure
view signals
run -all
